/**
 * ORGANIZATION VUEX
 */

export const FETCH_ORGANIZATION_WATERSHED = "FETCH_ORGANIZATION_WATERSHED";

/**
 * SELECTION VUEX
 */

export const SET_ALL_STATIONS = "SET_ALL_STATIONS";

/**
 * DATA VUEX
 */

export const ADD_STATION_DATA = "ADD_STATION_DATA";
export const FETCH_STATION_DATA = "FETCH_STATION_DATA";
