/**
 * ORGANIZATION VUEX
 */

export const LOADING_WATERSHED = "LOADING_WATERSHED";
export const SET_ACTIVE_ORGANIZATION = `SET_ACTIVE_ORGANIZATION`;
export const SET_WATERSHED = `SET_WATERSHED`;

/**
 * SELECTION VUEX
 */

export const ALL_RIVER_FORKS = "ALL_RIVER_FORKS";
export const ALL_LOCAL_WATERSHEDS = "ALL_LOCAL_WATERSHEDS";
export const ALL_LOCAL_WATERBODIES = "ALL_LOCAL_WATERBODIES";
export const ALL_STATION_NAMES = "ALL_STATION_NAMES";
export const SELECT_ACTIVE_PARAM = "SELECT_ACTIVE_PARAM";
export const SELECT_SECONDARY_PARAM = "SELECT_SECONDARY_PARAM";
export const SET_YEAR_RANGE = "SET_YEAR_RANGE";
export const SELECT_SINGLE_YEAR = "SELECT_SINGLE_YEAR";
export const SET_CHART_TYPE = "SET_CHART_TYPE";

/**
 * UI VUEX
 */

export const SET_ERROR_MSG = "SET_ERROR_MSG";
export const CLEAR_ERROR_MSG = "CLEAR_ERROR_MSG";
export const CLEAR_ALL_MSG = "CLEAR_ALL_MSG";
export const IS_LOADING = "IS_LOADING";
export const SHOW_YEAR_SELECTION = "SHOW_YEAR_SELECTION";
export const CLEAR_COOKIE_MSG = "CLEAR_COOKIE_MSG";
export const TAKE_TOUR = "TAKE_TOUR";
export const TOGGLE_STATION_INFO_MODAL = "TOGGLE_STATION_INFO_MODAL";

/**
 * DATA VUEX
 */

export const REMOVE_STATION = "REMOVE_STATION";
export const SELECT_STATION = "SELECT_STATION";
export const PROVIDE_APOLLO = "PROVIDE_APOLLO";
export const GENERATE_KEY = "GENERATE_KEY";
