/**
 * ORGANIZATION VUEX
 */

export const LOADING_WATERSHED = "LOADING_WATERSHED";
export const SET_ACTIVE_ORGANIZATION = `SET_ACTIVE_ORGANIZATION`;
export const SET_WATERSHED = `SET_WATERSHED`;

/**
 * SELECTION VUEX
 */

export const ALL_RIVER_FORKS = "ALL_RIVER_FORKS";
export const ALL_LOCAL_WATERSHEDS = "ALL_LOCAL_WATERSHEDS";
export const ALL_LOCAL_WATERBODIES = "ALL_LOCAL_WATERBODIES";
export const ALL_STATION_NAMES = "ALL_STATION_NAMES";
